controllers/AdvertisementsController.php
<?php
namespace app\controllers;

use app\consts\Permission;
use app\models\records\Advertisement;
use app\models\search\AdvertisementSearch;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

/**
 * AdvertisementsController implements the CRUD actions for Advertisement model.
 */
class AdvertisementsController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create', 'update', 'delete', 'my'],
                        'roles' => [Permission::ADS_MANAGE],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'view'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create', 'my'],
                        'roles' => [Permission::ADS_CREATE],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['update', 'delete'],
                        'roles' => [Permission::ADS_MANAGE_OWN_ADS],
                        'roleParams' => function () {
                            return ['advertisement' => Advertisement::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                ],
                'denyCallback' => function ($rule, $action) {
                    throw new \Exception(Yii::t('app', 'You are not allowed to access this page'));
                },
            ],
        ];
    }

    /**
     * Lists all Advertisement models.
     * @return string the rendering result.
     */
    public function actionIndex()
    {
        $searchModel = new AdvertisementSearch();
        $searchModel->published = true;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all My Advertisement models.
     * @return string the rendering result.
     */
    public function actionMy()
    {
        $searchModel = new AdvertisementSearch();
        $searchModel->user_id = Yii::$app->user->id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('my', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Advertisement model.
     * @param int $id   Advertisement id
     * @return string the rendering result of the 'view' view
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView(int $id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Advertisement model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return Response|string Response object from redirection if creation was successfull
     *                         or rendering result of the 'create' view if not.
     */
    public function actionCreate()
    {
        $model = new Advertisement();
        $model->user_id = Yii::$app->user->id;
        $model->published = true;

        if ($model->loadFromPost() && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Advertisement model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id   Advertisement id
     * @return Response|string Response object from redirection if update was successfull
     *                         or rendering result if not.
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate(int $id)
    {
        $model = $this->findModel($id);

        if ($model->loadFromPost() && $model->validate()) {
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes or restores an existing Advertisement model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id       Advertisement id
     * @param string $view  View string identifier
     * @return Response Response object from redirection
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete(int $id, string $view)
    {
        $model = $this->findModel($id);
        $model->deleted = !$model->deleted;
        $model->save();
        return $this->redirect([$view]);
    }

    /**
     * Finds the Advertisement model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id       Advertisement id
     * @return Advertisement the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel(int $id) : Advertisement
    {
        $model = Advertisement::findOne($id);
        if ($model == null || $model->deleted) {
            throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
        }
        return $model;
    }
}

controllers/ProjectsController.php
<?php
namespace app\controllers;

use app\consts\Param;
use app\consts\Permission;
use app\mail\Emails;
use app\models\forms\UploadForm;
use app\models\records\Document;
use app\models\records\Project;
use app\models\records\ProjectDocument;
use app\models\records\User;
use app\models\search\ProjectSearch;
use app\utils\storage\ProjectStorage;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UploadedFile;

/**
 * ProjectsController implements the CRUD actions for Project model.
 */
class ProjectsController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                    'status-update' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view'],
                        'roles' => ['?', '@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['my'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create'],
                        'roles' => [Permission::PROJECT_CREATE],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['delete'],
                        'roles' => [Permission::PROJECT_DELETE],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['update', 'send', 'request-to-run'],
                        'roles' => [Permission::PROJECT_UPDATE_OWN_PROJECT],
                        'roleParams' => function () {
                            return ['project' => Project::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['send-documents'],
                        'roles' => [Permission::PROJECT_SEND_DOCUMENTS],
                        'roleParams' => function () {
                            return ['project' => Project::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['update', 'update-content', 'advice-document', 'send', 'send-documents', 'request-to-run'],
                        'roles' => [Permission::PROJECT_UPDATE],
                        'roleParams' => function () {
                            return ['project' => Project::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['update-content'],
                        'roles' => [Permission::PROJECT_UPDATE_CONTENT],
                        'roleParams' => function () {
                            return ['project' => Project::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['advice-document'],
                        'roles' => [Permission::PROJECT_UPDATE_ADVICE],
                        'roleParams' => function () {
                            return ['project' => Project::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['status-update', 'run'],
                        'roles' => [Permission::PROJECT_UPDATE_STATUS],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['upload', 'upload-defence', 'delete-document'],
                        'roles' => [Permission::PROJECT_UPLOAD_FILE],
                        'roleParams' => function () {
                            return ['project' => Project::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                ],
                'denyCallback' => function ($rule, $action) {
                    throw new \Exception(Yii::t('app', 'You are not allowed to access this page'));
                },
            ],
        ];
    }

    /**
     * Lists all Project models.
     * @return string the rendering result.
     */
    public function actionIndex()
    {
        $searchModel = new ProjectSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all user Project models.
     * @return string the rendering result.
     */
    public function actionMy()
    {
        $searchModelMyProjects = new ProjectSearch();
        $dataProviderMyProjects = $searchModelMyProjects->search([
            $searchModelMyProjects->formName() => ['supervisorIds' => Yii::$app->user->id]
        ]);

        return $this->render('my', [
            'searchModelMyProjects' => $searchModelMyProjects,
            'dataProviderMyProjects' => $dataProviderMyProjects,
        ]);
    }

    /**
     * Displays a single Project model.
     * @param int $id   Project id
     * @return string the rendering result.
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView(int $id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Project model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string the rendering result.
     */
    public function actionCreate()
    {
        $model = new Project();
        $model->scenario = Project::SCENARIO_CREATE;
        $model->supervisorIds = Yii::$app->user->id;

        if ($model->loadFromPost() && $model->save()) {
            Yii::$app->session->addFlash('success', Yii::t('app', 'Saved'));
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Project model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id   Project id
     * @return Response|string  Response object from redirection if action was successfull
     *                          or rendering result if not.
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate(int $id)
    {
        $model = $this->findModel($id);
        $model->scenario = Project::SCENARIO_DRAFT;

        if (Yii::$app->request->post()) {
            $model->consultantIds = [];
            $model->memberIds = [];

            if ($model->loadFromPost() && $model->save()) {
                Yii::$app->session->addFlash('success', Yii::t('app', 'Updated'));
                return $this->redirect(['view', 'id' => $model->id]);

            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Update project status by AJAX request.
     * @param int $id   Project id
     * @return Response|string  Response object from redirection to view if no data from post were loaded
     *                          or response object for the request
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionStatusUpdate(int $id)
    {
        $model = $this->findModel($id);
        $model->scenario = Project::SCENARIO_STATUS_UPDATE;

        $previousState = $model->state;

        if ($model->loadFromPost()) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            if ($model->requested_to_run) $model->requested_to_run = false;

            if ($model->save()) {
                /** @var \app\models\records\ProjectStateHistory $lastState */
                $lastState = $model->getLastState();
                $lastState->comment = Yii::$app->request->post('statusComment');
                $lastState->save();

                if ($previousState != $model->state) {
                    foreach ($model->getActiveUsers()->all() as $user) {
                        Emails::projectStateChanged($model, $previousState, $user);
                    }
                }

                return ['output' => Yii::t('app', $model->state), 'message' => ''];
            }

            return ['output' => '', 'message' => Yii::t('app', 'Validation error')];
        }

        return $this->redirect(['view', 'id' => $model->id]);
    }

    /**
     * Updates content of an existing Project model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id   Project id
     * @return Response|string  Response object from redirection if action was successfull
     *                          or the rendering result of the update-content view
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdateContent(int $id)
    {
        $model = $this->findModel($id);

        if ($model->loadFromPost() && $model->save()) {
            Yii::$app->session->addFlash('success', Yii::t('app', 'Updated'));
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update-content', [

views/site/_advertisements.php
<?php

use app\models\records\Advertisement;
use kartik\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $advertisements yii\data\ActiveDataProvider */

?>
<div class="advertisements-index">

    <h1><?= Html::encode(Yii::t('app', 'New Advertisements')) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $advertisements,
        'bordered' => false,
        'headerRowOptions' => ['class' => 'hidden'],
        'striped' => false,
        'summary' => '',
        'columns' => [
            [
                'attribute' => 'title',
                'label' => false,
                'format' => 'raw',
                'filter' => false,
                'value' => function ($model) {
                    return Yii::$app->controller->renderPartial('_advertisements_model-view', ['model' => $model]);
                },
            ],
            [
                'attribute' => 'type',
                'label' => false,
                'filter' => Html::checkboxList('type', 'value', [
                    Advertisement::TYPE_PERSON => Yii::t('app', 'person'),
                    Advertisement::TYPE_PROJECT => Yii::t('app', 'project'),
                ]),
                'value' => function ($model) {
                    return Yii::t('app', $model->type);
                },
                'contentOptions' => function ($model) {
                    return ['width' => '70'];
                },
            ],
        ],
    ]); ?>

</div>

views/site/_advertisements_model-view.php
<?php

use app\models\records\AdvertisementComment;
use app\utils\DateTime;
use app\widgets\UserLinks;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model \app\models\records\Advertisement */

$dataProvider = new ActiveDataProvider(['query' => $model->getAdComments()]);
$commentsName = 'comments-' . $model->id;
$keywords = "";
if ($model->keywords != "") {
    foreach (explode(',', $model->keywords) as $value) {
        $keywords .= Html::a('#' . $value, Url::to(['advertisements/index', 'AdvertisementSearch[keywords]' => $value])) . ' ';
    }
}
?>

<h3><?= Html::a($model->title, ['advertisements/view', 'id' => $model->id]) ?></h3>

<p>
    <small><?= UserLinks::widget([UserLinks::USERS => $model->user]) ?></small>
    <small class="pull-right"><?= DateTime::from($model->updated_at)->format(DateTime::DATETIME) ?></small>
</p>

<p><?= $model->contentMarkdownProcessed ?></p>

views/site/_inbox.php
<?php

use app\consts\Permission;
use app\models\records\Project;
use app\models\records\DefenceDate;
use app\models\records\DefenceAttendance;
use app\models\records\Proposal;
use app\models\records\ProposalVote;
use app\utils\DateTime;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $inboxProjects yii\data\ActiveDataProvider */
/* @var $inboxProposals yii\data\ActiveDataProvider */
/* @var $inboxDefenceDates yii\data\ActiveDataProvider */

?>
<div class="inbox-index">

    <h1><?= Html::encode(Yii::t('app', 'Inbox')) ?></h1>

    <?php Pjax::begin(); ?>

    <?php if (Yii::$app->user->can(Permission::INBOX_PROJECTS)) { ?>
        <?= GridView::widget([
            'dataProvider' => $inboxProjects,
            'summary' => '',
            'columns' => [
                [
                    'label' => Yii::t('app', 'Project ID'),
                    'attribute' => 'short_name',
                    'format' => 'raw',
                    'value' => function (Project $model) {
                        return Html::a(Html::encode($model->short_name), ['projects/view', 'id' => $model->id]);
                    },
                ],
                [
                    'label' => Yii::t('app', 'State'),
                    'attribute' => 'state',
                    'value' => function (Project $model) {
                        return Yii::t('app', $model->state);
                    },
                    'filter' => Project::getOptionsStates(),
                ],
                [
                    'label' => Yii::t('app', 'State from'),
                    'attribute' => 'updated_at',
                    'value' => function(Project $model) {
                        if ($model->lastState == null) return Yii::$app->formatter->asDate(strtotime($model->updated_at), DateTime::YII_DATE);
                        return Yii::$app->formatter->asDate(strtotime($model->lastState->updated_at), DateTime::YII_DATE);
                    },
                ],
                [
                    'value' => function($model) {
                        $now = new DateTime();
                        if ($model->deadline && $model->deadline < $now) return Yii::t('app', 'After deadline');
                        else if ($model->requested_to_run == true) return Yii::t('app', 'Request to run');
                        else if ($model->waiting_for_proposal_evaluation == true) return Yii::t('app', 'Waiting For Proposal Evaluation');
                    },
                    'visible' => Yii::$app->user->can(Permission::PROJECT_UPDATE_STATUS),
                ],
            ],
        ]); ?>
    <?php } ?>

    <?= GridView::widget([
        'dataProvider' => $inboxProposals,
        'summary' => '',
        'columns' => [
            [
                'label' => Yii::t('app', 'Project ID'),
                'attribute' => 'short_name',
                'format' => 'raw',
                'value' => function (Proposal $model) {
                    return Html::a(Html::encode($model->project->short_name), ['projects/view', 'id' => $model->project->id]);
                }
            ],
            [
                'label' => Yii::t('app', 'My vote'),
                'format' => 'text',
                'value' => function(Proposal $model) {
                    $vote = $model->getProposalVoteByUserId(Yii::$app->getUser()->getId());
                    if ($vote) {
                        return ProposalVote::getVoteLabel($vote->vote);
                    }
                    else {
                        return ProposalVote::getVoteLabel('');
                    }
                }
            ],
            [
                'label' => Yii::t('app', 'Proposal'),
                'format' => 'raw',
                'value' => function(Proposal $model) {
                    $vote = $model->getProposalVoteByUserId(Yii::$app->getUser()->getId());
                    if ($vote == null) {
                        return Html::a(Yii::t('app', 'Please vote here'), ['proposals/view', 'id' => $model->id]);
                    } else {
                        return Html::a(Yii::t('app', 'Proposal'), ['proposals/view', 'id' => $model->id]);
                    }
                },
                'visible' => function(Proposal $model) {
                    return Yii::$app->user->can(Permission::PROPOSAL_VOTE, ['proposal' => $model]);
                },
            ],
        ],
    ]); ?>

    <?= GridView::widget([
        'dataProvider' => $inboxDefenceDates,
        'summary' => '',
        'columns' => [
            [
                'label' => Yii::t('app', 'Defence Dates'),
                'attribute' => 'short_name',
                'format' => 'raw',
                'value' => function (DefenceDate $model) {
                    $date = new DateTime($model->date);
                    return Html::a($date->format(DateTime::DATE), ['defence-dates/update', 'id' => $model->id]);
                }
            ],
            [
                'label' => Yii::t('app', 'My vote'),
                'format' => 'text',
                'value' => function(DefenceDate $model) {
                    $attendance = $model->getDefenceAttendanceByUserId(Yii::$app->getUser()->getId());
                    return DefenceAttendance::getVoteLabel($attendance->vote);
                }
            ],
            [
                'format' => 'raw',
                'value' => function($model) {
                    $attendance = $model->getDefenceAttendanceByUserId(Yii::$app->getUser()->getId());
                    if ($attendance->vote == DefenceAttendance::VOTE_UNKNOWN) {
                        return Html::a(Yii::t('app', 'Please vote here'), ['defence-dates/update', 'id' => $model->id]);
                    } else return '';
                },
                'visible' => Yii::$app->user->can(Permission::DEFENCES_VOTE_ABOUT_DATE),
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/site/_my-projects.php
<?php

use app\consts\Permission;
use app\models\records\Project;
use app\utils\DateTime;
use kartik\grid\GridView;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $myProjects yii\data\ActiveDataProvider */

?>
<div class="projects-index">

    <p class="pull-right">
         <?php if (Yii::$app->user->can(Permission::PROJECT_CREATE)) : ?>
            <?= Html::a(Yii::t('app', 'Create Project'), ['/projects/create'], ['class' => 'btn btn-success']) ?>
        <?php endif; ?>
    </p>

    <h1><?= Html::encode(Yii::t('app', 'My Projects')) ?></h1>

    <?php Pjax::begin(); ?>

    <?= GridView::widget([
        'dataProvider' => $myProjects,
        'hover' => true,
        //'summary' => '',
        'columns' => [
            [
                'attribute' => 'name',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a(Html::encode($model->name), ['projects/view', 'id' => $model->id]);
                },
            ],
            [
                'attribute' => 'short_name',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a(Html::encode($model->short_name), ['projects/view', 'id' => $model->id]);
                },
            ],
            [
                'label' => Yii::t('app', 'State'),
                'attribute' => 'state',
                'value' => function ($model) {
                    return Yii::t('app', $model->state);
                },
                'filter' => Project::getOptionsStates(),
            ],
            [
                'label' => Yii::t('app', 'State from'),
                'attribute' => 'updated_at',
                'value' => function ($model) {
                    if ($model->lastState == null) return Yii::$app->formatter->asDate(strtotime($model->updated_at), DateTime::YII_DATE);
                    return Yii::$app->formatter->asDate(strtotime($model->lastState->updated_at), DateTime::YII_DATE);
                },
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>

</div>

views/site/_news.php
<?php

use app\consts\Permission;
use app\models\records\News;
use app\utils\DateTime;
use yii\helpers\Html;
use yii\helpers\Markdown;

/* @var $this yii\web\View */
/* @var $searchModel app\models\NewsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->registerCssFile('@web/css/news/index.css');

$canManageNews = Yii::$app->user->can(Permission::NEWS_MANAGE);

?>
<div class="news-index">

    <?php if ($canManageNews) {
        echo Html::a(Yii::t('app', 'Create News'), ['/news/create'], ['class' => 'btn btn-success pull-right']);
    } ?>

    <h1><?= Html::encode(Yii::t('app', 'News')) ?></h1>

    <?php

    /**
     * @var \app\models\records\News $value
     */
    foreach ($news as $key => $value) {
        if (Yii::$app->user->isGuest && !$value->public) continue;
        ?>
        <div class="news-active-record <?= $value->type == News::TYPE_IMPORTANT ? "news-important" : "news-normal"; ?>">

            <?php if ($canManageNews) { ?>
                <div class="pull-right">
                    <?= Html::a('<span class="glyphicon glyphicon-pencil"></span>', ["news/update?id=" . $value->id]) ?>
                    <?= Html::a('<span class="glyphicon glyphicon-trash"></span>', ["news/delete?id=" . $value->id], ['data' => [
                        'confirm' => Yii::t('app', 'Are you sure to delete this item?'),
                        'method' => 'post'
                    ]]) ?>
                </div>
            <?php 
        } ?>

            <strong><?= $value->getLocalTitle() ?></strong>
            <span class="news-important-label">
                <?= $value->type == News::TYPE_IMPORTANT ? "(" . Yii::t('app', 'important') . ")" : ""; ?>
            </span>
            <span class="news-date"><?= DateTime::from($value->updated_at)->format(DateTime::DATE) ?></span>

            <div class="news-content"><?= Markdown::process(Html::encode($value->getLocalContent())) ?>&nbsp;</div>
        </div>
        <?php

    }
    ?>
</div>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use app\consts\Permission;

/* @var $this yii\web\View */
/* @var $news */
/* @var $advertisements */
/* @var $inboxProjects yii\data\ActiveDataProvider*/
/* @var $inboxDefenceDates yii\data\ActiveDataProvider*/
/* @var $inboxProposals yii\data\ActiveDataProvider*/
/* @var $myProjects yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Software projects MFF UK course NPRG023');
?>
<div class="site-index">
    <div class="body-content">
        <div class="row">
            <div class="col-lg-12 intro">
                <?= Yii::t('app', 'intro');?>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <?php if (Yii::$app->user->can(Permission::INBOX_LIST)) { ?>
                    <?= $this->render('_inbox', [
                        'inboxProjects' => $inboxProjects,
                        'inboxDefenceDates' => $inboxDefenceDates,
                        'inboxProposals' => $inboxProposals
                    ]); ?>
                <?php 
            } ?>
                <?= $this->render('_news', [
                    'news' => $news
                ]); ?>
            </div>
            <div class="col-lg-6">
                <?php
                if (Yii::$app->user->id && $myProjects->getCount()) {
                    echo $this->render('_my-projects', [
                        'myProjects' => $myProjects,
                    ]);
                }
                ?>
                <?= $this->render('_advertisements', [
                    'advertisements' => $advertisements,
                ]); ?>
            </div>
        </div>
    </div>
</div>

views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app', 'Request password reset');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Yii::t('app', 'Please fill out your email. A link to reset password will be sent there.') ?></p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton(Yii::t('app', 'Send'), ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>