controllers/ProjectsController.php
<?php
namespace app\controllers;

use app\consts\Param;
use app\consts\Permission;
use app\mail\Emails;
use app\models\forms\UploadForm;
use app\models\records\Document;
use app\models\records\Project;
use app\models\records\ProjectDocument;
use app\models\records\User;
use app\models\search\ProjectSearch;
use app\utils\storage\ProjectStorage;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UploadedFile;

/**
 * ProjectsController implements the CRUD actions for Project model.
 */
class ProjectsController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                    'status-update' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view'],
                        'roles' => ['?', '@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['my'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create'],
                        'roles' => [Permission::PROJECT_CREATE],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['delete'],
                        'roles' => [Permission::PROJECT_DELETE],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['update', 'send', 'request-to-run'],
                        'roles' => [Permission::PROJECT_UPDATE_OWN_PROJECT],
                        'roleParams' => function () {
                            return ['project' => Project::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['send-documents'],
                        'roles' => [Permission::PROJECT_SEND_DOCUMENTS],
                        'roleParams' => function () {
                            return ['project' => Project::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['update', 'update-content', 'advice-document', 'send', 'send-documents', 'request-to-run'],
                        'roles' => [Permission::PROJECT_UPDATE],
                        'roleParams' => function () {
                            return ['project' => Project::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['update-content'],
                        'roles' => [Permission::PROJECT_UPDATE_CONTENT],
                        'roleParams' => function () {
                            return ['project' => Project::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['advice-document'],
                        'roles' => [Permission::PROJECT_UPDATE_ADVICE],
                        'roleParams' => function () {
                            return ['project' => Project::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['status-update', 'run'],
                        'roles' => [Permission::PROJECT_UPDATE_STATUS],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['upload', 'upload-defence', 'delete-document'],
                        'roles' => [Permission::PROJECT_UPLOAD_FILE],
                        'roleParams' => function () {
                            return ['project' => Project::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                ],
                'denyCallback' => function ($rule, $action) {
                    throw new \Exception(Yii::t('app', 'You are not allowed to access this page'));
                },
            ],
        ];
    }

    /**
     * Lists all Project models.
     * @return string the rendering result.
     */
    public function actionIndex()
    {
        $searchModel = new ProjectSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all user Project models.
     * @return string the rendering result.
     */
    public function actionMy()
    {
        $searchModelMyProjects = new ProjectSearch();
        $dataProviderMyProjects = $searchModelMyProjects->search([
            $searchModelMyProjects->formName() => ['supervisorIds' => Yii::$app->user->id]
        ]);

        return $this->render('my', [
            'searchModelMyProjects' => $searchModelMyProjects,
            'dataProviderMyProjects' => $dataProviderMyProjects,
        ]);
    }

    /**
     * Displays a single Project model.
     * @param int $id   Project id
     * @return string the rendering result.
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView(int $id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Project model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string the rendering result.
     */
    public function actionCreate()
    {
        $model = new Project();
        $model->scenario = Project::SCENARIO_CREATE;
        $model->supervisorIds = Yii::$app->user->id;

        if ($model->loadFromPost() && $model->save()) {
            Yii::$app->session->addFlash('success', Yii::t('app', 'Saved'));
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Project model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id   Project id
     * @return Response|string  Response object from redirection if action was successfull
     *                          or rendering result if not.
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate(int $id)
    {
        $model = $this->findModel($id);
        $model->scenario = Project::SCENARIO_DRAFT;

        if (Yii::$app->request->post()) {
            $model->consultantIds = [];
            $model->memberIds = [];

            if ($model->loadFromPost() && $model->save()) {
                Yii::$app->session->addFlash('success', Yii::t('app', 'Updated'));
                return $this->redirect(['view', 'id' => $model->id]);

            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Update project status by AJAX request.
     * @param int $id   Project id
     * @return Response|string  Response object from redirection to view if no data from post were loaded
     *                          or response object for the request
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionStatusUpdate(int $id)
    {
        $model = $this->findModel($id);
        $model->scenario = Project::SCENARIO_STATUS_UPDATE;

        $previousState = $model->state;

        if ($model->loadFromPost()) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            if ($model->requested_to_run) $model->requested_to_run = false;

            if ($model->save()) {
                /** @var \app\models\records\ProjectStateHistory $lastState */
                $lastState = $model->getLastState();
                $lastState->comment = Yii::$app->request->post('statusComment');
                $lastState->save();

                if ($previousState != $model->state) {
                    foreach ($model->getActiveUsers()->all() as $user) {
                        Emails::projectStateChanged($model, $previousState, $user);
                    }
                }

                return ['output' => Yii::t('app', $model->state), 'message' => ''];
            }

            return ['output' => '', 'message' => Yii::t('app', 'Validation error')];
        }

        return $this->redirect(['view', 'id' => $model->id]);
    }

    /**
     * Updates content of an existing Project model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id   Project id
     * @return Response|string  Response object from redirection if action was successfull
     *                          or the rendering result of the update-content view
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdateContent(int $id)
    {
        $model = $this->findModel($id);

        if ($model->loadFromPost() && $model->save()) {
            Yii::$app->session->addFlash('success', Yii::t('app', 'Updated'));
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update-content', [

views/proposals/_form.php
<?php

use app\models\forms\UploadForm;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model \app\models\records\Proposal */
/* @var $form yii\widgets\ActiveForm */

$markdownIcon = '<img src="' . Yii::$app->homeUrl . 'img/md.png" style="width: 20px;" title="markdown"/>';
?>

<div class="proposals-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php $uploadModel = new UploadForm(); ?>

    <?= $form->field($model, 'documentMarkdown')->textarea(['rows' => '4'])->label($markdownIcon) ?>

    <?= ($model->document->fallback_path) ?
        Yii::t('app', 'Uploaded file: ') . Html::a(Yii::t('app', 'PDF'), $model->document->fallback_path) : ('')
    ?>

    <?= $form->field($uploadModel, 'files')->fileInput(['multiple' => false, 'accept' => 'application/pdf'])->label(Yii::t('app', 'Upload file')) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/proposals/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model \app\models\search\ProposalSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="proposals-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'updated_at') ?>

    <?= $form->field($model, 'deleted') ?>

    <?= $form->field($model, 'project_id') ?>

    <?php // echo $form->field($model, 'document_id') ?>

    <?php // echo $form->field($model, 'state') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/proposals/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model \app\models\records\Proposal */

$this->title = Yii::t('app', 'Create Proposal');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Proposals'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="proposals-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/proposals/index.php
<?php

use app\utils\DateTime;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\grid\DataColumn;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel \app\models\search\ProposalSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Proposals');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="proposals-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'project.name',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a(Html::encode($model->project->name), ['projects/view', 'id' => $model->project->id]);
                }
            ],
            'project.short_name',
            [
                'label' => Yii::t('app', 'Supervisor'),
                'attribute' => 'supervisors',
                'value' => function ($model) {
                    $supervisors = '';
                    if (isset($model->project->supervisors)) {
                        $supervisorArray = [];
                        /** @var \app\models\records\User $supervisor */
                        foreach ($model->project->supervisors as $supervisor)
                        {
                            $supervisorArray[] = Html::encode($supervisor->getNameWithEmail());
                        }
                        $supervisors = implode(',', $supervisorArray);
                    }
                    return $supervisors;
                },
            ],
            [
                'class' => DataColumn::class,
                'headerOptions' => ['width' => '160'],
                'format' => 'text',
                'header' => Yii::t('app', 'Date'),
                'value' => function ($model) {
                    $date = new DateTime($model->created_at);
                    return $date->format(DateTime::DATETIME);
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}',
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

views/proposals/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \app\models\records\Proposal */

$this->title = Yii::t('app', 'Update Proposal');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Projects'), 'url' => ['projects/index']];
$this->params['breadcrumbs'][] = ['label' => $model->project->name, 'url' => ['projects/view', 'id' => $model->project->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update Proposal');
?>
<div class="proposals-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>