controllers/AdCommentsController.php
<?php
namespace app\controllers;

use app\consts\Permission;
use app\mail\Emails;
use app\models\records\AdvertisementComment;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

/**
 * AdCommentsController implements the CRUD actions for AdComment model.
 */
class AdCommentsController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create', 'delete'],
                        'roles' => [Permission::ADS_MANAGE_COMMENTS],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create'],
                        'roles' => [Permission::ADS_CREATE_COMMENT],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['delete'],
                        'roles' => [Permission::ADS_MANAGE_OWN_COMMENTS],
                        'roleParams' => function () {
                            return ['ad-comment' => AdvertisementComment::findOne(Yii::$app->request->get('id'))];
                        },
                    ],
                ],
                'denyCallback' => function ($rule, $action) {
                    throw new \Exception(Yii::t('app', 'You are not allowed to access this page'));
                },
            ],
        ];
    }

    /**
     * Lists all AdComment models.
     * @return string the rendering result.
     */
    public function actionIndex()
    {
        $query = AdvertisementComment::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $query->andFilterWhere([
            'deleted' => false,
        ]);

        return $this->render('index', [
            'dataProviderComment' => $dataProvider,
        ]);
    }

    /**
     * Creates a new AdComment model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return Response Response object from redirection
     */
    public function actionCreate()
    {
        $model = new AdvertisementComment();
        $model->user_id = Yii::$app->user->id;

        if ($model->loadFromPost() && $model->save()) {
            $advertisement = $model->ad;
            if ($advertisement != null && $advertisement->deleted == false && $advertisement->subscribed_via_email) {
                Emails::advertisementAddComment($model);
            }
        }

        return $this->redirect(['advertisements/index']);
    }

    /**
     * Deletes or restores an existing AdComment model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id   AdComment id
     * @return Response Response object from redirection
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete(int $id)
    {
        $model = $this->findModel($id);
        if ($model != null) {
            $model->deleted = !$model->deleted;
            $model->save();
        }
        return $this->redirect(['advertisements/index']);
    }

    /**
     * Finds the AdComment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id   AdComments id
     * @return AdvertisementComment the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel(int $id) : AdvertisementComment
    {
        if (($model = AdvertisementComment::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

}

views/ad-comments/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $modelComment \app\models\records\AdvertisementComment */
/* @var $form yii\widgets\ActiveForm */
/* @var $adId integer */
?>

<div class="ad-comments-form">

    <?php $form = ActiveForm::begin(['action' => ['/ad-comments/create']]); ?>

    <?= $form->field($modelComment, 'ad_id')->textInput(['value' => $adId, 'class' => 'hidden'])->label(false) ?>
    <div class="form-group row">
        <div class="col-lg-8 col-md-8 col-sm-8">
            <?= $form->field($modelComment, 'content')->textarea(['rows' => '1', 'placeholder' => Yii::t("app", "Write your comment")])->label(false) ?>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
            <?= Html::submitButton(Yii::t('app', 'Send'), ['class' => 'btn btn-success']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/ad-comments/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $modelComment \app\models\records\AdvertisementComment */
/* @var $adId integer */
?>
<div class="ad-comments-create">

    <?= $this->render('_form', [
        'modelComment' => $modelComment,
        'adId' => $adId,
    ]) ?>

</div>

views/ad-comments/index.php
<?php

use kartik\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use yii\helpers\Html;
use app\utils\DateTime;
use app\consts\Permission;
use \app\widgets\UserLinks;

/* @var $this yii\web\View */
/* @var $dataProviderComment yii\data\ActiveDataProvider */
/* @var $adId integer */
?>
<div class="ad-comments-index">

    <?php Pjax::begin(); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'headerRowOptions' => ['class' => 'hidden'],
        'showOnEmpty' => false,
        'emptyText' => '<table><tbody></tbody></table>',
        'columns' => [
            [
                'attribute' => 'content',
                'format' => 'raw',
                'label' => false,
                'value' => function ($model) {
                    return
                        "<p><small>"
                        . UserLinks::widget([UserLinks::USERS => $model->user])
                        . "</small>"
                        . "<span class=\"pull-right\"><small class=\"text-muted\">"
                        . DateTime::from($model->updated_at)->format(DateTime::DATETIME)
                        . "</small></span></p>"
                        . " <p>" . Html::encode($model->content) . "</p>";
                },
            ],
            [
                'class' => 'kartik\grid\ActionColumn',
                'template' => '{delete}',
                'dropdownOptions' => ['class' => 'pull-right'],
                'vAlign' => GridView::ALIGN_TOP,
                'visible' => Yii::$app->user->id, // user is log in
                'buttons' => [
                    'delete' => function ($url, $model) {
                        // check permissions
                        if (Yii::$app->user->can(Permission::ADS_MANAGE_COMMENTS) || Yii::$app->user->id == $model->user->id) {
                            $url = Url::to(['ad-comments/delete', 'id' => $model->id]);
                            return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                'title' => Yii::t('app', 'Delete'),
                                'data-confirm' => Yii::t('app', 'Are you sure to delete this item?'),
                                'data-method' => 'post',
                            ]);
                        }
                    }
                ],
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>
</div>